apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test2
  namespace: default
spec:
  selector:
    matchLabels:
      app: jenkins-test2
  template:
    metadata:
      labels:
        app: jenkins-test2
    spec:
      containers:
      - image: swr.na-mexico-1.myhuaweicloud.com/test-swr/jenkins-test2:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        command:
          - sleep
        args:
          - '1000'
        name: jenkins-test2
        env:
        - name: branch
      imagePullSecrets:
        - name: default-secret
